/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package net.codebuilders

class App {

    static TestFileServer server

    static void main(String[] args) {

        server = new TestFileServer()

        server.start(8080)

        // Add a shutdown hook to stop the server gracefully
        Runtime.getRuntime().addShutdownHook(new Thread(() -> {
            System.out.println("Stopping server...")
            server.stop(0); // Stop immediately
        }))

    }

    String getGreeting() {
        return 'Hello World!'
    }

}
